# Generated by Django 6.0.2 on 2026-02-28 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='board',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
